<?php $_product = Mage::registry('current_product') ?>

<?php $curProductCategoryIds = $_product->getCategoryIds() ?>

<?php $selectedCategoryIds = (Mage::getStoreConfig('FMRS_section/FMRS_group/category'))//Ids of selected category in System->Configuration?>

<?php $selCategoryIds = explode(",", $selectedCategoryIds); ?>

<?php foreach($curProductCategoryIds as $curProductCategoryId) {?>

<?php foreach($selCategoryIds as $selCategoryId) {?>

<?php if ($curProductCategoryId == $selCategoryId): ?>
<!--this is your button -->
<!--FMRS-BUTTON:BEGIN-->
<link   href='http://static.findmyringsize.com/shared/buttons/fmrs-buttons.css' rel='stylesheet' type='text/css' />
<a id='ringsizer' class='fmrs-bsize-l fmrs-bdes-bl9  fmrs-button-host'  alt='Find Your Ring Size' href='http://sizer.findmyringsize.com' target='_blank' >Find Your Ring Size</a> 
<!--FMRS-BUTTON:END-->

<?php break;endif; ?>
<?php }?>
<?php }?>